### PR TITLE
Fixing tollboth test

### PR DESCRIPTION
**Pull request by Mathiou04**
Hello @didip,
working on #74, I noticed that some tests in tollboth_test.go were not working properly as BuildKeys returns an empty slice (due to IPLookup default behaviour).
I tried to fix it like this, what do you think?

If you have time, I am also interested in understanding why when RemoteAddr is set first (default behaviour) in IPLookup, it bypasses the header checks even if it doesn't find an IP address.

Thanks!

### CODE REVIEW

**Comment by didip** [comment]
I am surprised that these tests are failing for you.

Re: why when RemoteAddr is set first (default behaviour) in IPLookup, it bypasses the header checks even if it doesn't find an IP address

^^ That's interesting, let me take a look.

**Comment by didip** [comment]
If `libstring.RemoteIP` could not find an IP address, it will simply return empty string.

I am not seeing inside `tollbooth.BuildKeys()`, how header check can be skipped.

**Comment by Mathiou04** [comment]
The tests are not failing for me in the master branch but when I changed some code I noticed they are not checking exactly what is expected (I think).

What happened is this:
- I started working on the `BuildKeys` method
- I made a change on the fields that were returned in the `[]string` value that should have made the tests fail
- tests didn't fail so I checked why

What I found on test `TestBasicAuthBuildKeys` is the following:
- `BuildKeys` returns an empty slice so the tests always pass even when changing the logic for the BasicAuth part of the `BuildKeys` method
- `BuildKeys` returns an empty slice because `libstring.RemoteIP` returns an empty string
- libstring.RemoteIP returns an empty slice because the default lookup starts with `RemoteAddr` and when entering the loop on `ipLookups`, if we are in the `RemoteAddr` case, we will always return from it (either `r.RemoteAddr` or `ip`)

To approximately check what I am saying I did the following:
- added a test on the length of `BuildKeys` to ensure we always have a non-empty string
- it made the test fail
- I fixed it by changing the default lookup, as it was done in `TestDefaultBuildKeys`

Tell me if what I wrote make sense or not!

**Comment by didip** [comment]
ok, give me some time to read your branch more carefully.

**Comment by Mathiou04** [comment]
Of course!

**Pull request merged**
