### PR TITLE
Embed time/rate, set RateLimit headers

### LINKED ISSUE #88: Configurable option for using ratelimit standardization proposal
## I wish

to be able to support via configuration the following standardization proposal: https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-ratelimit-headers

gh repo: https://github.com/ietf-wg-httpapi/ratelimit-headers

This is currently implemented by envoy-proxy, kong and 3scale.

## The spec

defines 3 ratelimit-headers, returning the current quota, remaining quota and delta-seconds before quota expires.

```
   RateLimit-Limit: 100
   RateLimit-Remaining: 50
   RateLimit-Reset: 60

```

### PR DESCRIPTION
**Pull request by paskal**
Will resolve #88 once done. I went the lazy way of embedding time/rate instead of rewriting it, function we need will be added in https://github.com/golang/go/issues/50035 in the future.

ToDo:
- [x] make `countLimitWithTokenBucketTTL` work
- [x] adjust Readme
- [x] add tests
- [x] manual tests

### CODE REVIEW

**Review by ioggstream — CHANGES_REQUESTED** [review]
Hi @paskal , thanks for the opportunity of reviewing your code!

iiuc there's a syntax issue that needs to be fixed: just return the 3 numbers without the `;w=1` parameter in this case.
For the rest it seems ok to me but I hadn't the time to run/test it.

Let me know, R.

**Comment by paskal** [comment]
I have a little time problem right now, I believe I would be able to finish this PR not earlier than mid-January.

**Comment by paskal** [comment]
I've got the first working version of the code, feel free to review it. It's not final, but the logic of the calculation won't change unless there are any problems.

**Comment by didip** [comment]
Looks good to me so far.

**Comment by paskal** [comment]
I found a way to simplify the code by calling the new functions instead of duplicating the code twice in the old and new ones, which removed the need for independent testing of the internal functions. As far as I can see, the only missing thing is the end-to-end test which will check that the limiter now returns the proper headers.

**Comment by paskal** [comment]
I think I got everything ready this time, ready for review. cc @ioggstream.

**Comment by ioggstream** [comment]
Hi! How can I build the patched version?

**Comment by paskal** [comment]
To use the changed version of the module, please run in the project using it:
```shell
git clone https://github.com/paskal/tollbooth.git -b ieft-headers
go mod edit -replace github.com/didip/tollbooth/v6=./tollbooth
```

**Comment by ioggstream** [comment]
I'm using [this script](https://gist.github.com/ioggstream/e0d475d3c71874bdfc6eb9b41d309243) syntax is ok. 


> ratelimit-remaining only raises ...
It seems I experience the same issue as you using this snippet

Remaining is always `1`

```
from requests import get
import time
header_fmt = lambda r: '\t'.join(v for k,v in r.headers.items() if "Ratelimit-" in k)

for i in range(1000): # 
    r = get("http://0.0.0.0:12345")
    print(r.status_code, header_fmt(r))
    if r.status_code != 200: time.sleep(1)
```

**Comment by paskal** [comment]
@didip do you by any chance have any familiarity with the rate-limiting stdlib code? I assume that some token calculation function with time should be used, but it's so non-trivial that I haven't found the right way to calculate it yet.

**Comment by ioggstream** [comment]
@paskal we are currently discussing https://github.com/ietf-wg-httpapi/ratelimit-headers/pull/81 
that is separating further quota information in another field.

iiuc this does not change anything on your side, right?
Thanks, R.

**Comment by paskal** [comment]
Correct. I plan to give the proper rate calculation another try today.

**Comment by paskal** [comment]
@ioggstream thanks a lot for your test script! I modified it a little:

```python
from requests import get
import time

rate_header = "Ratelimit-"

header_fmt = lambda r: '\t'+'\t\t'.join(v for k, v in r.headers.items() if rate_header in k)
once = False

for i in range(10):
    r = get("http://0.0.0.0:12345")
    if not once:
        once = True
        print('Code\t','\t'.join(k[len(rate_header):] for k, v in r.headers.items() if rate_header in k))
    print(r.status_code, header_fmt(r))
    if r.status_code != 200: time.sleep(1)

```

Thanks to the comment in https://github.com/golang/go/issues/50035#issuecomment-1013416864 I found a way to calculate tokens correctly (and sooner rather than later it will be available in the library itself so we won't need to embed it anymore).

Here is the result:

```
Code     Limit  Remaining       Reset
200     3               2               1
200     3               1               1
200     3               0               1
429     3               0               1
200     3               2               1
200     3               1               1
200     3               0               1
429     3               0               1
200     3               2               1
200     3               1               1
```

I'll fix the tests and implement the latest proposal you mentioned, and then it will be ready for review.

**Comment by paskal** [comment]
I think the current version is suitable for review, cc @ioggstream @didip.

**Comment by paskal** [comment]
Another gentle ping for review.

**Comment by didip** [comment]
That is a big effort. Good job. This looks fine to me. It will have to be available on major version considering how big the changes are. ok?

Anyone else wants to review? +1 from me.

**Comment by paskal** [comment]
Thanks for the review! It doesn't change the logic in any way and only adds a few headers. As far as I can predict, the worst-case scenario is that we would be reporting incorrect metrics under some conditions and not following the RFC draft properly.

I would propose settling on the new minor version if you asked me.

**Comment by didip** [comment]
@paskal That said, the underlying rate limiter engine is changed to the vendored time.Limiter , right? I think that's worth to be called out under a major version.

**Comment by paskal** [comment]
It's the same thing as before but embedded plus a single method. It's your call.

**Comment by paskal** [comment]
@didip unfortunately v7.0.0 won't work as you haven't changed the go.mod and imports inside the program from v6 to v7 before tagging it.

**Pull request merged**
