### PR TITLE
Switch to expirable-cache

### LINKED ISSUE #84: go-cache used for limiter leaking goroutines
Hi @didip, thanks for your amazing work!

Using [goleak](https://github.com/uber-go/goleak) in [remark42](https://github.com/umputun/remark42) repo I found that we have tons of leaking goroutines in tests from the go-cache package. I've replaced it with internal implementation in [go-pkgz/lcw](https://github.com/go-pkgz/lcw) and switched remark42 to it only to discover that some other dependency of it utilizes `limiter` from this package, which in turn use go-cache.

This is how go-cache suppose to kill its goroutine: https://github.com/patrickmn/go-cache/blob/master/cache.go#L1123
It utilizes [runtime.SetFinalizer](https://golang.org/pkg/runtime/#SetFinalizer) which would work (as I understood it) only if we'll remove pointers to created instance of go-cache and then would wait for it to be collected by Garbage Collector.

This doesn't work well with tests and I don't know how well it works in "normal" flows. So, here is my question: would you accept a PR with a switch to some other expirable cache which doesn't rely on spawning goroutines, this way minimizing the footprint of the limiter?

### PR DESCRIPTION
**Pull request by paskal**
Resolves #84. I haven't found a cache that wouldn't spawn goroutines and would have the unlimited size so I published one similar to the one I contributed to hashicorp/golang-lru in https://github.com/hashicorp/golang-lru/pull/68 as a separate project and switched tollbooth to it.

tollbooth API stays exactly the same, the only API difference is `ExpirableOptions.ExpireJobInterval` is unused becomes and becomes deprecated.

The big difference with previously used go-cache is the following: expired entries are deleted only on new `Set` calls on the same cache.

The only alternative to preserve exact same behavior as previously I could think of is calling DeleteExpired in this package and giving users the ability to terminate these goroutines using `Close()` call on a Limiter, which is kind of ugly but would do the trick. However, creating `Close()` function would allow us to switch to a number of different caches that provide their own `Close()` functions and then just call them inside our `Close`.

Please let me know what you think about that.

### CODE REVIEW

**Comment by paskal** [comment]
Sure, all tests are passing. Everything works the same way as before aside from potentially using more memory but not spawning goroutines in great number. Merging #85 will run tests for every PR as well as master.

**Comment by paskal** [comment]
My apologies, one thing I forgot: tests behavior is consistent with the current master.

`Test_Issue48_RequestTerminatedEvenOnLowVolumeOnSameIP` is failing in the master and failing in this branch as well, I haven't looked into fixing it and I don't know if it's set up properly in the first place. I would suggest reopening #48 in case you think this test shouldn't fail.

**Comment by didip** [comment]
ok, should #85 be merged first?

**Comment by paskal** [comment]
It would show `Test_Issue48_RequestTerminatedEvenOnLowVolumeOnSameIP` failure so it would provide no value for this PR. I think we should merge #86 and #85 in any order, either disable or fix the failing test and only then release `v6.0.0`.

**Comment by paskal** [comment]
Actually, I have a suggestion of merging #85 and fixing #48 test, releasing `v5.2.0`, and only then merging this one to release `v6.0.0`. Otherwise we'll entangle bugfix with changed behavior, which is bad.

**Comment by didip** [comment]
ok, don't worry about issue 48 then. Sounds like a good idea.

**Comment by paskal** [comment]
@didip I don't know how to fix it and I don't think it's correct, it's reliably failing with "429 too many requests" on very first request. I would suggest removing this test altogether and then I'll rebase this branch on new master to show that tests are not failing.
If you want, I can prepare PR which will remove the test.

**Comment by didip** [comment]
@paskal Don't worry about it, I am testing it right now. If it still doesn't make sense, I will remove the test.

**Comment by didip** [comment]
@paskal The test in master is fixed now, you can copy-paste `tollbooth_bug_report_test.go` to your branch if you want.

**Comment by paskal** [comment]
Thanks a lot! Now it's green and tests verify that. I would suggest releasing 5.2.0 with green tests first and only then merging this PR.

**Comment by didip** [comment]
Git tag v5.2.0 is pushed

**Comment by didip** [comment]
Git tag v6.0.0 is pushed

**Pull request merged**
